assign5:		assign5.cpp glslprogram.cpp glslprogram.hpp
		g++ -w -o assign5 assign5.cpp glslprogram.cpp -lm -framework OpenGL -framework GLUT -Wno-deprecated-declarations -Wno-c++11-compat-deprecated-writable-strings
